### ISSUE TITLE
Feedback vom 12.03.2018

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong#42]
- [x] - Keine Feuerkämpfe langweilig
- [x] - Scout keine Chance was zu finden?
- [x] - Einzigartiges Spielkonzept cool
- [x] - Pilot sollte nich sehen, ob sein GPS überträgt oder nicht - für Opfor sonst zu schwer
- [x] - Langsameres Tracking unter Bäumen evtl statt gar nicht
- [x] - Blutspur deutlicher findbar machen? Als Pilot rennt man schneller [weniger Stamina?!]
- [x] - Spawn Freeze wäre sinnvoll
- [x] - Als Pilot sehr spannend, als Opfor aber auch trotz keine Gefechte
- [x] - Beide Seiten lustig, Brückenkurve fies
- [x] - Blufor Fahrzeuge sind nicht respawned?
- [x] - Vorher heilen müssen wäre sinnvoll, damit Gegenseite Gelegenheit hat aufzuholen
- [x] - Combat Pace zieht Ausdauer [Ausdauer erhöhen?]
- [x] - Andere Map (Altis?) für offenere Flächen und mehr Geballer [wontdofornow]
- [x] - Pilot nur 2-3 Flares geben, damit Lagerfeuer Sinn machen
- [x] - Stühle bei Kamera können nicht besetzt werden
- [x] - Pilot will sich vor Kamera bewegen können und evtl Zipties für Opfor? [Opfor Cmd hatte schon welche?]
- [x] - TFAR Bug? Nur noch über Funk hörbar statt Direct Speech [cantfix]
- [x] - Searchlight Actions bugged
- [x] - sehr atmosphärisch aber wenig Action
- [x] - Opfor Aufholaktion dauert zu lange, wenn er einmal im Heli sitzt
- [x] - Opfor ist unterlegen
- [x] - Tracker stärker machen
- [x] - Erste Runde für Opfor frustrierend
- [x] - Viel längere Filmzeit nötig
- [x] - Filmzeit nicht länger machen, damit keine Katzenwache entsteht und immer Endkampf forciert wird
- [x] - Schneise durch den Wald hauen für Opfor [wontdofornow]

**Comment by nomisum** [comment]
Heli als Extraction Fzg verbieten?
Kamera kaputtschießbar machen?

**Comment by Fusselwurm** [comment]
Hmm wären vllt Minenfelder sinnvoll, um Kartengebiete zu sperren, und die Spieler auf kleinere Bereiche zu konzentrieren

**Comment by nomisum** [comment]
Ich hab ein bisschen Angst, dass der Pilot da reinläuft, dh ich müsste viele Warn-Schilder setzen, was den Object Count hochtreibt. Oder zusätzlich eine Einblendung. Welche Bereiche würdest du sperren?

**Comment by Fusselwurm** [comment]
jetz nur mal so rumgesponnen:
* ich würd den ungefähren Bereich der jetzigen no-fly-zone (NFZ) nehmen, und dort random kleine Minenfelder legen (100m*100m)
* den Bereich außerhalb der NFZ großflächig verminen
    * nur kleine Durchgänge lassen
    *  oder einfach alles abseits der Straßen verminen (dh wenn Spieler > 30m weg von Straße -> bumm)
* die NFZ auf das opfor-spawn-Sperrgebiet + 300m Radius beschränken
* als weitere Maßnahmen aus den obengenannten Sachen:
    * Vorbereitungszeit 5'
    * beim verwundeten Piloten iwie die Stamina/ Bewegungsgeschwindigkeit runter, oder ihn ab und an mal zwangsbremsen (Schwächeanfall?) 
    * und die Spuren besser auffindbar machen

Das stärkt Blufor (sind schneller im Gebiet) und Opfor (finden schneller den Piloten), führt zu mehr Kontakten (Gebiet eingeschränkt) und dazu daß der Pilot nich einfach im Dauerlauf über die ganze Karte hoppeln kann, bis er Opfor abgehängt hat und der Heli ihn einfach rausziehen kann (was gestern abend passiert ist). Damits nicht ganz unrealistisch ist, müssen die Ausfallstraßen frei bleiben –– aber deren Anzahl ist ja begrenzt, und für Opfor wär das dann leichter sperrbar. Kleine Minenfelder im Spielgebiet könnten dafür sorgen, daß nicht immer alle nur gradeaus hintereinander durch den Dschungel wetzen,sondern man auch mal Haken schlagen/ sich umdrehen / nen andern Weg probieren muß. Die Minenfelder würd ich mindestens für Opfor (vllt auch blufor) sichtbar auf der Map  plazieren

Variieren müßte man diese Parameter (Größe der minenfreie Zone, Pilotenausdauer) vmtl dann mit der Spielerzahl.

Minenfelder technisch:
* auf der Karte markiert
* evtl in der Nähe des Spielers lokal (!) Schilder spawnen & wieder despawnen wenn er sich entfernt

**Comment by nomisum** [comment]
Hmmm.. NFZ *muss* über der Absturzstelle auch sein, sonst ist Blufor in 5min da, ehe Opfor aus den Puschen gekommen ist. D.h. der Kreis darf nicht zu klein sein. Meinethalben muss sie nicht gar so groß sein, wie bisher – andererseits ist der Heli schon fähig auch innerhalb zu fliegen mit Risiko. Ich überlege eher, dass ich die AA-Stellungen markiere und damit auch zu validen Angriffszielen mache (Opfor müsste den Status tracken können).

Da das erste Spiel, wo Ainer nicht auf GPS geachtet hat und die Reichweite der Tracker größer war, sehr viel actionreicher war, glaube ich gar nicht mal, dass wir sooo große Änderungen brauchen um wieder zurück zu Feuergefechten zu kommen.

Pilot braucht auf jeden Fall einen Stamina Nerf mit seiner Verletzung. Ich denke da an 50% von dem, was man beim Leute tragen verliert (150% statt 200%) – beim Wunde zuhalten verliert er momentan 300%. Das dürfte eigentlich auch schon reichen, damit die Spur leichter trackbar bleibt.

Minenfelder würden den Dschungel wirklich unbefahrbar machen, das grenzt jetzt schon an Folter mit Fahrzeugen da durchzukommen. Wenn man jetzt noch alle Nase lang vor einem Minenfeld abdrehen muss, kommt man gar nicht mehr voran.

**Comment by nomisum** [comment]
Nein, aber sie können aus der Luft sehr gut erkennen wo sie ist durch das Wrack, Feuerschein sieht man über die Object Render Distance hinaus. Und sie hätten wiederum keinen Anhaltspunkt, wenn sie das nicht hätten. Und ich hätte kein Intro mehr /o\

**Comment by nomisum** [comment]
put all the things i want to do in extra tickets, closing here.
