### ISSUE TITLE
Consider implications of removing magic marker on pilot

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong#62]
I like the idea of having no extra magic marker on the pilot or his bodybag, if he dies. The less magic, the less rules.

No magic marker means blufor also needs GPS tracker with same range settings (1000m if pilot on foot, 10000m if he is in a vehicle) OR some other method to find their guy.

No Marker on the body could be tricky in edge case situations, e.g. pilot dies in water/explodes in vehicle in water, body is moved to nearest shore. Therefore it might be necessary to mark his corpse with a chemlight and something else (tbd) in daylight

**Comment by nomisum** [comment]
GPS tracker for blufor might not be as hard for opfor as one might think.

1. Opfor is still first at crash site, bc Blufor has to refuel their heli first
2. As 1) implicates, Pilot will try to stay hidden in the beginning
3. Later, Pilot always has to consider between revealing himself to both sides (best case >1000m from opfor scout) or stay low
4. GPS wont be totally controllable anymore, meaning Opfor still has some hints every once in a while, when GPS activates despite no clear sky
5. GPS for blufor I would consider available only in heli

**Comment by nomisum** [comment]
thoughts @Fusselwurm ?

**Comment by nomisum** [comment]
I forgot to mention the pilot needs in any case to be stabilized for a few minutes before he can enter the helicopter. Stabilizing can be done with any medic. This prevents quick insertion/extraction movement by Blufor.

My only worry for Blufor is that Opfor can easily kill the pilot on sight and gains an advantage instead of having to worry for safe extraction as they can only carry the dead pilot by vehicle, thus being visible to blufor GPS. The marker solution was there to prevent opfor from killing the guy instantly.

Swarm of crows is a brilliant idea.

**Comment by Fusselwurm** [comment]
How about introducing a penalty for killing the pilot?
Propaganda value depends on him being alive, so let's just say that filming a corpse takes considerably longer to achieve victory.

live pilot => 5 minutes
dead pilot => 25 minutes

that way, no additional magic is necessary for tracking the dead pilot, as the opponents will almost certainly have time to stage a counter-attack

**Comment by nomisum** [comment]
Great idea. You can tradeoff a quicker and safer extraction versus a longer showdown. Only abuse possibility would be a teamkill from blufor to gain time.

**Comment by Fusselwurm** [comment]
> a teamkill from blufor to gain time.

like "no medic here but we need to extract NOW, so lets just kill you and load your corpse…"?

**Comment by nomisum** [comment]
No, like
> our guy is in opfors hands and they are close to their camera point - lets kill him so they have to wait longer when filming him.

or even
> they are filming him, lets give him the bullet to buy us time

**Comment by nomisum** [comment]
(could be prevented by teamkill penalty – reducing the time again for opfor)

**Comment by nomisum** [comment]
Ticket created https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/issues/63
