### ISSUE TITLE
Type Array, expected Number,Not a Number - fn_bodyBagHintRemove l6

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong#65]
```
22:01:57 Error in expression <emlight_handle", objNull];

if (_handle >= 0) then {
[_handle] call CBA_fnc_remo>
22:01:57   Error position: <>= 0) then {
[_handle] call CBA_fnc_remo>
22:01:57   Error >=: Type Array, expected Number,Not a Number
22:01:57 File grad_pilotTracking\functions\client\fn_bodyBagHintRemove.sqf [GRAD_pilotTracking_fnc_bodyBagHintRemove], line 6
```

**Comment by dedmen** [comment]
https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/blob/d5db6f18696d39e258586fb4fc0a26a6a7c3f9ce/grad_pilotTracking/functions/client/fn_bodyBagHintAdd.sqf#L4

https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/blob/d5db6f18696d39e258586fb4fc0a26a6a7c3f9ce/grad_flies/client/fn_flies.sqf#L14

https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/blob/d5db6f18696d39e258586fb4fc0a26a6a7c3f9ce/grad_flies/client/fn_flies.sqf#L82

Fix: 
https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/blob/d5db6f18696d39e258586fb4fc0a26a6a7c3f9ce/grad_pilotTracking/functions/client/fn_bodyBagHintAdd.sqf#L3
->
`private _handle = [_bodybag] call GRAD_flies_fnc_flies select 1;`


You should use `private` more often.

**Comment by nomisum** [comment]
doing that already.. most of the time. almost. pinky promise.

but thanks for the crazy fast heads up.

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/commit/3dee3b3eedfc19a876cca7231baffc3af0576692
