### ISSUE TITLE
yellow "meet up" markers at [0,0,0]

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong#76]
Possibly flare markers? 

* Blufor
* no JIP
* respawned once

**Comment by nomisum** [comment]
I believe this is a locality issue and the projectile is not known to the server.

Have to transfer the location and not the object.

**Comment by nomisum** [comment]
https://github.com/gruppe-adler/TvT_Rattenfalle.prei_khmaoch_luong/blob/setcaptive/grad_pilotTracking/functions/client/fn_initPilot.sqf#L45
